name: Build and push image to Github Container Registry

on:
  repository_dispatch:
    types: [build-push-docker]

jobs:
  docker-build-push:
    name: Push Automat API docs to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release' }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/robokopu24/api-docs:${{ github.event.client_payload.tag }}
            ghcr.io/robokopu24/api-docs:latest
