name: Generate and deploy docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]
    
permissions:
  contents: write
  pages: write
  id-token: write
    
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Write current date to environment variable
        run: echo "DATE=$(date +'%Y-%m-%d-%I.%M.%S%p')" >> $GITHUB_ENV

      - name: Add git user configuration
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Fetch staging from remote
        run: |
          git fetch
          git switch staging
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Fetch newest Automat OpenAPI document and metadata
        run: npm run preprocess
        
      - name: Generate Docusaurus mdx files
        run: |
          npm run clean-api-docs automat
          npm run gen-api-docs automat
          
      - name: Rewrite sidebar.js
        run: npm run rearrange-sidebar
        
      - name: Remove "Introduction" page
        run: rm ./docs/automat/automat.info.mdx || echo "Introduction docs page is already deleted"

      - name: Check for untracked files
        run: |
          git add -A
          if git status | grep -q 'Changes to be committed'; then
            echo "UPDATED=true" >> $GITHUB_ENV
          else
            echo "Docs have not been updated, nothing has changed." > $GITHUB_STEP_SUMMARY
          fi

      # Only run the next two steps if there were changes detected by `git status` in the previous step
      - name: Commit changes to staging
        if: ${{ env.UPDATED == 'true' }}
        run: |
          git commit -m "$(echo 'Update documentation - ${{ env.DATE }}')"
          git push

      - name: Build the site
        if: ${{ env.UPDATED == 'true' }}
        run: npm run build
        
      - name: Setup GH Pages
        uses: actions/configure-pages@v1
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
